/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as privatehomeRouteRouteImport } from './routes/(private)/(home)/route'
import { Route as LoginOtpIndexRouteImport } from './routes/login/otp/index'
import { Route as privatehomeIndexRouteImport } from './routes/(private)/(home)/index'
import { Route as privatehomeExpensesIndexRouteImport } from './routes/(private)/(home)/expenses/index'

const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const privatehomeRouteRoute = privatehomeRouteRouteImport.update({
  id: '/(home)',
  getParentRoute: () => privateRouteRoute,
} as any)
const LoginOtpIndexRoute = LoginOtpIndexRouteImport.update({
  id: '/otp/',
  path: '/otp/',
  getParentRoute: () => LoginRouteRoute,
} as any).lazy(() =>
  import('./routes/login/otp/index.lazy').then((d) => d.Route),
)
const privatehomeIndexRoute = privatehomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privatehomeRouteRoute,
} as any)
const privatehomeExpensesIndexRoute = privatehomeExpensesIndexRouteImport
  .update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => privatehomeRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(private)/(home)/expenses/index.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/login': typeof LoginRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/': typeof privatehomeIndexRoute
  '/login/otp': typeof LoginOtpIndexRoute
  '/expenses': typeof privatehomeExpensesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginIndexRoute
  '/': typeof privatehomeIndexRoute
  '/login/otp': typeof LoginOtpIndexRoute
  '/expenses': typeof privatehomeExpensesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/(private)/(home)': typeof privatehomeRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/(private)/(home)/': typeof privatehomeIndexRoute
  '/login/otp/': typeof LoginOtpIndexRoute
  '/(private)/(home)/expenses/': typeof privatehomeExpensesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/login/' | '/' | '/login/otp' | '/expenses'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/login/otp' | '/expenses'
  id:
    | '__root__'
    | '/(private)'
    | '/login'
    | '/(private)/(home)'
    | '/login/'
    | '/(private)/(home)/'
    | '/login/otp/'
    | '/(private)/(home)/expenses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateRouteRoute: typeof privateRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/(private)/(home)': {
      id: '/(private)/(home)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privatehomeRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/login/otp/': {
      id: '/login/otp/'
      path: '/otp'
      fullPath: '/login/otp'
      preLoaderRoute: typeof LoginOtpIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/(private)/(home)/': {
      id: '/(private)/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privatehomeIndexRouteImport
      parentRoute: typeof privatehomeRouteRoute
    }
    '/(private)/(home)/expenses/': {
      id: '/(private)/(home)/expenses/'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof privatehomeExpensesIndexRouteImport
      parentRoute: typeof privatehomeRouteRoute
    }
  }
}

interface privatehomeRouteRouteChildren {
  privatehomeIndexRoute: typeof privatehomeIndexRoute
  privatehomeExpensesIndexRoute: typeof privatehomeExpensesIndexRoute
}

const privatehomeRouteRouteChildren: privatehomeRouteRouteChildren = {
  privatehomeIndexRoute: privatehomeIndexRoute,
  privatehomeExpensesIndexRoute: privatehomeExpensesIndexRoute,
}

const privatehomeRouteRouteWithChildren =
  privatehomeRouteRoute._addFileChildren(privatehomeRouteRouteChildren)

interface privateRouteRouteChildren {
  privatehomeRouteRoute: typeof privatehomeRouteRouteWithChildren
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privatehomeRouteRoute: privatehomeRouteRouteWithChildren,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
  LoginOtpIndexRoute: typeof LoginOtpIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
  LoginOtpIndexRoute: LoginOtpIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateRouteRoute: privateRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
