/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as privatehomeRouteRouteImport } from './routes/(private)/(home)/route'
import { Route as privateBudgetIdRouteRouteImport } from './routes/(private)/$budgetId/route'
import { Route as LoginOtpIndexRouteImport } from './routes/login/otp/index'
import { Route as privatehomeIndexRouteImport } from './routes/(private)/(home)/index'
import { Route as privateBudgetIdIndexRouteImport } from './routes/(private)/$budgetId/index'
import { Route as privateBudgetIdExpensesGroupsRouteRouteImport } from './routes/(private)/$budgetId/expenses-groups/route'
import { Route as privatehomeBudgetsIndexRouteImport } from './routes/(private)/(home)/budgets/index'
import { Route as privateBudgetIdIncomesIndexRouteImport } from './routes/(private)/$budgetId/incomes/index'
import { Route as privateBudgetIdExpensesGroupsIndexRouteImport } from './routes/(private)/$budgetId/expenses-groups/index'
import { Route as privateBudgetIdIncomesUpdateIndexRouteImport } from './routes/(private)/$budgetId/incomes/update/index'
import { Route as privateBudgetIdIncomesCreateIndexRouteImport } from './routes/(private)/$budgetId/incomes/create/index'
import { Route as privateBudgetIdExpensesGroupsEditIndexRouteImport } from './routes/(private)/$budgetId/expenses-groups/edit/index'
import { Route as privateBudgetIdExpensesGroupsCreateIndexRouteImport } from './routes/(private)/$budgetId/expenses-groups/create/index'
import { Route as privateBudgetIdExpensesGroupsExpenseGroupIdIndexRouteImport } from './routes/(private)/$budgetId/expenses-groups/$expense-group-id/index'
import { Route as privateBudgetIdExpensesGroupsExpenseGroupIdUpdateIndexRouteImport } from './routes/(private)/$budgetId/expenses-groups/$expense-group-id/update/index'
import { Route as privateBudgetIdExpensesGroupsExpenseGroupIdCreateIndexRouteImport } from './routes/(private)/$budgetId/expenses-groups/$expense-group-id/create/index'

const privatehomeBudgetsCreateLazyRouteImport = createFileRoute(
  '/(private)/(home)/budgets/create',
)()
const privatehomeBudgetsEditBudgetIdLazyRouteImport = createFileRoute(
  '/(private)/(home)/budgets/edit/$budgetId',
)()

const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const privatehomeRouteRoute = privatehomeRouteRouteImport.update({
  id: '/(home)',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateBudgetIdRouteRoute = privateBudgetIdRouteRouteImport.update({
  id: '/$budgetId',
  path: '/$budgetId',
  getParentRoute: () => privateRouteRoute,
} as any)
const LoginOtpIndexRoute = LoginOtpIndexRouteImport.update({
  id: '/otp/',
  path: '/otp/',
  getParentRoute: () => LoginRouteRoute,
} as any).lazy(() =>
  import('./routes/login/otp/index.lazy').then((d) => d.Route),
)
const privatehomeIndexRoute = privatehomeIndexRouteImport
  .update({
    id: '/',
    path: '/',
    getParentRoute: () => privatehomeRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(private)/(home)/index.lazy').then((d) => d.Route),
  )
const privateBudgetIdIndexRoute = privateBudgetIdIndexRouteImport
  .update({
    id: '/',
    path: '/',
    getParentRoute: () => privateBudgetIdRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(private)/$budgetId/index.lazy').then((d) => d.Route),
  )
const privateBudgetIdExpensesGroupsRouteRoute =
  privateBudgetIdExpensesGroupsRouteRouteImport.update({
    id: '/expenses-groups',
    path: '/expenses-groups',
    getParentRoute: () => privateBudgetIdRouteRoute,
  } as any)
const privatehomeBudgetsIndexRoute = privatehomeBudgetsIndexRouteImport
  .update({
    id: '/budgets/',
    path: '/budgets/',
    getParentRoute: () => privatehomeRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(private)/(home)/budgets/index.lazy').then((d) => d.Route),
  )
const privateBudgetIdIncomesIndexRoute = privateBudgetIdIncomesIndexRouteImport
  .update({
    id: '/incomes/',
    path: '/incomes/',
    getParentRoute: () => privateBudgetIdRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(private)/$budgetId/incomes/index.lazy').then(
      (d) => d.Route,
    ),
  )
const privateBudgetIdExpensesGroupsIndexRoute =
  privateBudgetIdExpensesGroupsIndexRouteImport
    .update({
      id: '/',
      path: '/',
      getParentRoute: () => privateBudgetIdExpensesGroupsRouteRoute,
    } as any)
    .lazy(() =>
      import('./routes/(private)/$budgetId/expenses-groups/index.lazy').then(
        (d) => d.Route,
      ),
    )
const privatehomeBudgetsCreateLazyRoute =
  privatehomeBudgetsCreateLazyRouteImport
    .update({
      id: '/budgets/create',
      path: '/budgets/create',
      getParentRoute: () => privatehomeRouteRoute,
    } as any)
    .lazy(() =>
      import('./routes/(private)/(home)/budgets/create.lazy').then(
        (d) => d.Route,
      ),
    )
const privateBudgetIdIncomesUpdateIndexRoute =
  privateBudgetIdIncomesUpdateIndexRouteImport
    .update({
      id: '/incomes/update/',
      path: '/incomes/update/',
      getParentRoute: () => privateBudgetIdRouteRoute,
    } as any)
    .lazy(() =>
      import('./routes/(private)/$budgetId/incomes/update/index.lazy').then(
        (d) => d.Route,
      ),
    )
const privateBudgetIdIncomesCreateIndexRoute =
  privateBudgetIdIncomesCreateIndexRouteImport
    .update({
      id: '/incomes/create/',
      path: '/incomes/create/',
      getParentRoute: () => privateBudgetIdRouteRoute,
    } as any)
    .lazy(() =>
      import('./routes/(private)/$budgetId/incomes/create/index.lazy').then(
        (d) => d.Route,
      ),
    )
const privateBudgetIdExpensesGroupsEditIndexRoute =
  privateBudgetIdExpensesGroupsEditIndexRouteImport
    .update({
      id: '/edit/',
      path: '/edit/',
      getParentRoute: () => privateBudgetIdExpensesGroupsRouteRoute,
    } as any)
    .lazy(() =>
      import('./routes/(private)/$budgetId/expenses-groups/edit/index.lazy').then(
        (d) => d.Route,
      ),
    )
const privateBudgetIdExpensesGroupsCreateIndexRoute =
  privateBudgetIdExpensesGroupsCreateIndexRouteImport
    .update({
      id: '/create/',
      path: '/create/',
      getParentRoute: () => privateBudgetIdExpensesGroupsRouteRoute,
    } as any)
    .lazy(() =>
      import('./routes/(private)/$budgetId/expenses-groups/create/index.lazy').then(
        (d) => d.Route,
      ),
    )
const privateBudgetIdExpensesGroupsExpenseGroupIdIndexRoute =
  privateBudgetIdExpensesGroupsExpenseGroupIdIndexRouteImport
    .update({
      id: '/$expense-group-id/',
      path: '/$expense-group-id/',
      getParentRoute: () => privateBudgetIdExpensesGroupsRouteRoute,
    } as any)
    .lazy(() =>
      import('./routes/(private)/$budgetId/expenses-groups/$expense-group-id/index.lazy').then(
        (d) => d.Route,
      ),
    )
const privatehomeBudgetsEditBudgetIdLazyRoute =
  privatehomeBudgetsEditBudgetIdLazyRouteImport
    .update({
      id: '/budgets/edit/$budgetId',
      path: '/budgets/edit/$budgetId',
      getParentRoute: () => privatehomeRouteRoute,
    } as any)
    .lazy(() =>
      import('./routes/(private)/(home)/budgets/edit.$budgetId.lazy').then(
        (d) => d.Route,
      ),
    )
const privateBudgetIdExpensesGroupsExpenseGroupIdUpdateIndexRoute =
  privateBudgetIdExpensesGroupsExpenseGroupIdUpdateIndexRouteImport
    .update({
      id: '/$expense-group-id/update/',
      path: '/$expense-group-id/update/',
      getParentRoute: () => privateBudgetIdExpensesGroupsRouteRoute,
    } as any)
    .lazy(() =>
      import('./routes/(private)/$budgetId/expenses-groups/$expense-group-id/update/index.lazy').then(
        (d) => d.Route,
      ),
    )
const privateBudgetIdExpensesGroupsExpenseGroupIdCreateIndexRoute =
  privateBudgetIdExpensesGroupsExpenseGroupIdCreateIndexRouteImport
    .update({
      id: '/$expense-group-id/create/',
      path: '/$expense-group-id/create/',
      getParentRoute: () => privateBudgetIdExpensesGroupsRouteRoute,
    } as any)
    .lazy(() =>
      import('./routes/(private)/$budgetId/expenses-groups/$expense-group-id/create/index.lazy').then(
        (d) => d.Route,
      ),
    )

export interface FileRoutesByFullPath {
  '/login': typeof LoginRouteRouteWithChildren
  '/$budgetId': typeof privateBudgetIdRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/$budgetId/expenses-groups': typeof privateBudgetIdExpensesGroupsRouteRouteWithChildren
  '/$budgetId/': typeof privateBudgetIdIndexRoute
  '/': typeof privatehomeIndexRoute
  '/login/otp': typeof LoginOtpIndexRoute
  '/budgets/create': typeof privatehomeBudgetsCreateLazyRoute
  '/$budgetId/expenses-groups/': typeof privateBudgetIdExpensesGroupsIndexRoute
  '/$budgetId/incomes': typeof privateBudgetIdIncomesIndexRoute
  '/budgets': typeof privatehomeBudgetsIndexRoute
  '/budgets/edit/$budgetId': typeof privatehomeBudgetsEditBudgetIdLazyRoute
  '/$budgetId/expenses-groups/$expense-group-id': typeof privateBudgetIdExpensesGroupsExpenseGroupIdIndexRoute
  '/$budgetId/expenses-groups/create': typeof privateBudgetIdExpensesGroupsCreateIndexRoute
  '/$budgetId/expenses-groups/edit': typeof privateBudgetIdExpensesGroupsEditIndexRoute
  '/$budgetId/incomes/create': typeof privateBudgetIdIncomesCreateIndexRoute
  '/$budgetId/incomes/update': typeof privateBudgetIdIncomesUpdateIndexRoute
  '/$budgetId/expenses-groups/$expense-group-id/create': typeof privateBudgetIdExpensesGroupsExpenseGroupIdCreateIndexRoute
  '/$budgetId/expenses-groups/$expense-group-id/update': typeof privateBudgetIdExpensesGroupsExpenseGroupIdUpdateIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginIndexRoute
  '/$budgetId': typeof privateBudgetIdIndexRoute
  '/': typeof privatehomeIndexRoute
  '/login/otp': typeof LoginOtpIndexRoute
  '/budgets/create': typeof privatehomeBudgetsCreateLazyRoute
  '/$budgetId/expenses-groups': typeof privateBudgetIdExpensesGroupsIndexRoute
  '/$budgetId/incomes': typeof privateBudgetIdIncomesIndexRoute
  '/budgets': typeof privatehomeBudgetsIndexRoute
  '/budgets/edit/$budgetId': typeof privatehomeBudgetsEditBudgetIdLazyRoute
  '/$budgetId/expenses-groups/$expense-group-id': typeof privateBudgetIdExpensesGroupsExpenseGroupIdIndexRoute
  '/$budgetId/expenses-groups/create': typeof privateBudgetIdExpensesGroupsCreateIndexRoute
  '/$budgetId/expenses-groups/edit': typeof privateBudgetIdExpensesGroupsEditIndexRoute
  '/$budgetId/incomes/create': typeof privateBudgetIdIncomesCreateIndexRoute
  '/$budgetId/incomes/update': typeof privateBudgetIdIncomesUpdateIndexRoute
  '/$budgetId/expenses-groups/$expense-group-id/create': typeof privateBudgetIdExpensesGroupsExpenseGroupIdCreateIndexRoute
  '/$budgetId/expenses-groups/$expense-group-id/update': typeof privateBudgetIdExpensesGroupsExpenseGroupIdUpdateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/(private)/$budgetId': typeof privateBudgetIdRouteRouteWithChildren
  '/(private)/(home)': typeof privatehomeRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/(private)/$budgetId/expenses-groups': typeof privateBudgetIdExpensesGroupsRouteRouteWithChildren
  '/(private)/$budgetId/': typeof privateBudgetIdIndexRoute
  '/(private)/(home)/': typeof privatehomeIndexRoute
  '/login/otp/': typeof LoginOtpIndexRoute
  '/(private)/(home)/budgets/create': typeof privatehomeBudgetsCreateLazyRoute
  '/(private)/$budgetId/expenses-groups/': typeof privateBudgetIdExpensesGroupsIndexRoute
  '/(private)/$budgetId/incomes/': typeof privateBudgetIdIncomesIndexRoute
  '/(private)/(home)/budgets/': typeof privatehomeBudgetsIndexRoute
  '/(private)/(home)/budgets/edit/$budgetId': typeof privatehomeBudgetsEditBudgetIdLazyRoute
  '/(private)/$budgetId/expenses-groups/$expense-group-id/': typeof privateBudgetIdExpensesGroupsExpenseGroupIdIndexRoute
  '/(private)/$budgetId/expenses-groups/create/': typeof privateBudgetIdExpensesGroupsCreateIndexRoute
  '/(private)/$budgetId/expenses-groups/edit/': typeof privateBudgetIdExpensesGroupsEditIndexRoute
  '/(private)/$budgetId/incomes/create/': typeof privateBudgetIdIncomesCreateIndexRoute
  '/(private)/$budgetId/incomes/update/': typeof privateBudgetIdIncomesUpdateIndexRoute
  '/(private)/$budgetId/expenses-groups/$expense-group-id/create/': typeof privateBudgetIdExpensesGroupsExpenseGroupIdCreateIndexRoute
  '/(private)/$budgetId/expenses-groups/$expense-group-id/update/': typeof privateBudgetIdExpensesGroupsExpenseGroupIdUpdateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/$budgetId'
    | '/login/'
    | '/$budgetId/expenses-groups'
    | '/$budgetId/'
    | '/'
    | '/login/otp'
    | '/budgets/create'
    | '/$budgetId/expenses-groups/'
    | '/$budgetId/incomes'
    | '/budgets'
    | '/budgets/edit/$budgetId'
    | '/$budgetId/expenses-groups/$expense-group-id'
    | '/$budgetId/expenses-groups/create'
    | '/$budgetId/expenses-groups/edit'
    | '/$budgetId/incomes/create'
    | '/$budgetId/incomes/update'
    | '/$budgetId/expenses-groups/$expense-group-id/create'
    | '/$budgetId/expenses-groups/$expense-group-id/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$budgetId'
    | '/'
    | '/login/otp'
    | '/budgets/create'
    | '/$budgetId/expenses-groups'
    | '/$budgetId/incomes'
    | '/budgets'
    | '/budgets/edit/$budgetId'
    | '/$budgetId/expenses-groups/$expense-group-id'
    | '/$budgetId/expenses-groups/create'
    | '/$budgetId/expenses-groups/edit'
    | '/$budgetId/incomes/create'
    | '/$budgetId/incomes/update'
    | '/$budgetId/expenses-groups/$expense-group-id/create'
    | '/$budgetId/expenses-groups/$expense-group-id/update'
  id:
    | '__root__'
    | '/(private)'
    | '/login'
    | '/(private)/$budgetId'
    | '/(private)/(home)'
    | '/login/'
    | '/(private)/$budgetId/expenses-groups'
    | '/(private)/$budgetId/'
    | '/(private)/(home)/'
    | '/login/otp/'
    | '/(private)/(home)/budgets/create'
    | '/(private)/$budgetId/expenses-groups/'
    | '/(private)/$budgetId/incomes/'
    | '/(private)/(home)/budgets/'
    | '/(private)/(home)/budgets/edit/$budgetId'
    | '/(private)/$budgetId/expenses-groups/$expense-group-id/'
    | '/(private)/$budgetId/expenses-groups/create/'
    | '/(private)/$budgetId/expenses-groups/edit/'
    | '/(private)/$budgetId/incomes/create/'
    | '/(private)/$budgetId/incomes/update/'
    | '/(private)/$budgetId/expenses-groups/$expense-group-id/create/'
    | '/(private)/$budgetId/expenses-groups/$expense-group-id/update/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateRouteRoute: typeof privateRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/(private)/(home)': {
      id: '/(private)/(home)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privatehomeRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/$budgetId': {
      id: '/(private)/$budgetId'
      path: '/$budgetId'
      fullPath: '/$budgetId'
      preLoaderRoute: typeof privateBudgetIdRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/login/otp/': {
      id: '/login/otp/'
      path: '/otp'
      fullPath: '/login/otp'
      preLoaderRoute: typeof LoginOtpIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/(private)/(home)/': {
      id: '/(private)/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privatehomeIndexRouteImport
      parentRoute: typeof privatehomeRouteRoute
    }
    '/(private)/$budgetId/': {
      id: '/(private)/$budgetId/'
      path: '/'
      fullPath: '/$budgetId/'
      preLoaderRoute: typeof privateBudgetIdIndexRouteImport
      parentRoute: typeof privateBudgetIdRouteRoute
    }
    '/(private)/$budgetId/expenses-groups': {
      id: '/(private)/$budgetId/expenses-groups'
      path: '/expenses-groups'
      fullPath: '/$budgetId/expenses-groups'
      preLoaderRoute: typeof privateBudgetIdExpensesGroupsRouteRouteImport
      parentRoute: typeof privateBudgetIdRouteRoute
    }
    '/(private)/(home)/budgets/': {
      id: '/(private)/(home)/budgets/'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof privatehomeBudgetsIndexRouteImport
      parentRoute: typeof privatehomeRouteRoute
    }
    '/(private)/$budgetId/incomes/': {
      id: '/(private)/$budgetId/incomes/'
      path: '/incomes'
      fullPath: '/$budgetId/incomes'
      preLoaderRoute: typeof privateBudgetIdIncomesIndexRouteImport
      parentRoute: typeof privateBudgetIdRouteRoute
    }
    '/(private)/$budgetId/expenses-groups/': {
      id: '/(private)/$budgetId/expenses-groups/'
      path: '/'
      fullPath: '/$budgetId/expenses-groups/'
      preLoaderRoute: typeof privateBudgetIdExpensesGroupsIndexRouteImport
      parentRoute: typeof privateBudgetIdExpensesGroupsRouteRoute
    }
    '/(private)/(home)/budgets/create': {
      id: '/(private)/(home)/budgets/create'
      path: '/budgets/create'
      fullPath: '/budgets/create'
      preLoaderRoute: typeof privatehomeBudgetsCreateLazyRouteImport
      parentRoute: typeof privatehomeRouteRoute
    }
    '/(private)/$budgetId/incomes/update/': {
      id: '/(private)/$budgetId/incomes/update/'
      path: '/incomes/update'
      fullPath: '/$budgetId/incomes/update'
      preLoaderRoute: typeof privateBudgetIdIncomesUpdateIndexRouteImport
      parentRoute: typeof privateBudgetIdRouteRoute
    }
    '/(private)/$budgetId/incomes/create/': {
      id: '/(private)/$budgetId/incomes/create/'
      path: '/incomes/create'
      fullPath: '/$budgetId/incomes/create'
      preLoaderRoute: typeof privateBudgetIdIncomesCreateIndexRouteImport
      parentRoute: typeof privateBudgetIdRouteRoute
    }
    '/(private)/$budgetId/expenses-groups/edit/': {
      id: '/(private)/$budgetId/expenses-groups/edit/'
      path: '/edit'
      fullPath: '/$budgetId/expenses-groups/edit'
      preLoaderRoute: typeof privateBudgetIdExpensesGroupsEditIndexRouteImport
      parentRoute: typeof privateBudgetIdExpensesGroupsRouteRoute
    }
    '/(private)/$budgetId/expenses-groups/create/': {
      id: '/(private)/$budgetId/expenses-groups/create/'
      path: '/create'
      fullPath: '/$budgetId/expenses-groups/create'
      preLoaderRoute: typeof privateBudgetIdExpensesGroupsCreateIndexRouteImport
      parentRoute: typeof privateBudgetIdExpensesGroupsRouteRoute
    }
    '/(private)/$budgetId/expenses-groups/$expense-group-id/': {
      id: '/(private)/$budgetId/expenses-groups/$expense-group-id/'
      path: '/$expense-group-id'
      fullPath: '/$budgetId/expenses-groups/$expense-group-id'
      preLoaderRoute: typeof privateBudgetIdExpensesGroupsExpenseGroupIdIndexRouteImport
      parentRoute: typeof privateBudgetIdExpensesGroupsRouteRoute
    }
    '/(private)/(home)/budgets/edit/$budgetId': {
      id: '/(private)/(home)/budgets/edit/$budgetId'
      path: '/budgets/edit/$budgetId'
      fullPath: '/budgets/edit/$budgetId'
      preLoaderRoute: typeof privatehomeBudgetsEditBudgetIdLazyRouteImport
      parentRoute: typeof privatehomeRouteRoute
    }
    '/(private)/$budgetId/expenses-groups/$expense-group-id/update/': {
      id: '/(private)/$budgetId/expenses-groups/$expense-group-id/update/'
      path: '/$expense-group-id/update'
      fullPath: '/$budgetId/expenses-groups/$expense-group-id/update'
      preLoaderRoute: typeof privateBudgetIdExpensesGroupsExpenseGroupIdUpdateIndexRouteImport
      parentRoute: typeof privateBudgetIdExpensesGroupsRouteRoute
    }
    '/(private)/$budgetId/expenses-groups/$expense-group-id/create/': {
      id: '/(private)/$budgetId/expenses-groups/$expense-group-id/create/'
      path: '/$expense-group-id/create'
      fullPath: '/$budgetId/expenses-groups/$expense-group-id/create'
      preLoaderRoute: typeof privateBudgetIdExpensesGroupsExpenseGroupIdCreateIndexRouteImport
      parentRoute: typeof privateBudgetIdExpensesGroupsRouteRoute
    }
  }
}

interface privateBudgetIdExpensesGroupsRouteRouteChildren {
  privateBudgetIdExpensesGroupsIndexRoute: typeof privateBudgetIdExpensesGroupsIndexRoute
  privateBudgetIdExpensesGroupsExpenseGroupIdIndexRoute: typeof privateBudgetIdExpensesGroupsExpenseGroupIdIndexRoute
  privateBudgetIdExpensesGroupsCreateIndexRoute: typeof privateBudgetIdExpensesGroupsCreateIndexRoute
  privateBudgetIdExpensesGroupsEditIndexRoute: typeof privateBudgetIdExpensesGroupsEditIndexRoute
  privateBudgetIdExpensesGroupsExpenseGroupIdCreateIndexRoute: typeof privateBudgetIdExpensesGroupsExpenseGroupIdCreateIndexRoute
  privateBudgetIdExpensesGroupsExpenseGroupIdUpdateIndexRoute: typeof privateBudgetIdExpensesGroupsExpenseGroupIdUpdateIndexRoute
}

const privateBudgetIdExpensesGroupsRouteRouteChildren: privateBudgetIdExpensesGroupsRouteRouteChildren =
  {
    privateBudgetIdExpensesGroupsIndexRoute:
      privateBudgetIdExpensesGroupsIndexRoute,
    privateBudgetIdExpensesGroupsExpenseGroupIdIndexRoute:
      privateBudgetIdExpensesGroupsExpenseGroupIdIndexRoute,
    privateBudgetIdExpensesGroupsCreateIndexRoute:
      privateBudgetIdExpensesGroupsCreateIndexRoute,
    privateBudgetIdExpensesGroupsEditIndexRoute:
      privateBudgetIdExpensesGroupsEditIndexRoute,
    privateBudgetIdExpensesGroupsExpenseGroupIdCreateIndexRoute:
      privateBudgetIdExpensesGroupsExpenseGroupIdCreateIndexRoute,
    privateBudgetIdExpensesGroupsExpenseGroupIdUpdateIndexRoute:
      privateBudgetIdExpensesGroupsExpenseGroupIdUpdateIndexRoute,
  }

const privateBudgetIdExpensesGroupsRouteRouteWithChildren =
  privateBudgetIdExpensesGroupsRouteRoute._addFileChildren(
    privateBudgetIdExpensesGroupsRouteRouteChildren,
  )

interface privateBudgetIdRouteRouteChildren {
  privateBudgetIdExpensesGroupsRouteRoute: typeof privateBudgetIdExpensesGroupsRouteRouteWithChildren
  privateBudgetIdIndexRoute: typeof privateBudgetIdIndexRoute
  privateBudgetIdIncomesIndexRoute: typeof privateBudgetIdIncomesIndexRoute
  privateBudgetIdIncomesCreateIndexRoute: typeof privateBudgetIdIncomesCreateIndexRoute
  privateBudgetIdIncomesUpdateIndexRoute: typeof privateBudgetIdIncomesUpdateIndexRoute
}

const privateBudgetIdRouteRouteChildren: privateBudgetIdRouteRouteChildren = {
  privateBudgetIdExpensesGroupsRouteRoute:
    privateBudgetIdExpensesGroupsRouteRouteWithChildren,
  privateBudgetIdIndexRoute: privateBudgetIdIndexRoute,
  privateBudgetIdIncomesIndexRoute: privateBudgetIdIncomesIndexRoute,
  privateBudgetIdIncomesCreateIndexRoute:
    privateBudgetIdIncomesCreateIndexRoute,
  privateBudgetIdIncomesUpdateIndexRoute:
    privateBudgetIdIncomesUpdateIndexRoute,
}

const privateBudgetIdRouteRouteWithChildren =
  privateBudgetIdRouteRoute._addFileChildren(privateBudgetIdRouteRouteChildren)

interface privatehomeRouteRouteChildren {
  privatehomeIndexRoute: typeof privatehomeIndexRoute
  privatehomeBudgetsCreateLazyRoute: typeof privatehomeBudgetsCreateLazyRoute
  privatehomeBudgetsIndexRoute: typeof privatehomeBudgetsIndexRoute
  privatehomeBudgetsEditBudgetIdLazyRoute: typeof privatehomeBudgetsEditBudgetIdLazyRoute
}

const privatehomeRouteRouteChildren: privatehomeRouteRouteChildren = {
  privatehomeIndexRoute: privatehomeIndexRoute,
  privatehomeBudgetsCreateLazyRoute: privatehomeBudgetsCreateLazyRoute,
  privatehomeBudgetsIndexRoute: privatehomeBudgetsIndexRoute,
  privatehomeBudgetsEditBudgetIdLazyRoute:
    privatehomeBudgetsEditBudgetIdLazyRoute,
}

const privatehomeRouteRouteWithChildren =
  privatehomeRouteRoute._addFileChildren(privatehomeRouteRouteChildren)

interface privateRouteRouteChildren {
  privateBudgetIdRouteRoute: typeof privateBudgetIdRouteRouteWithChildren
  privatehomeRouteRoute: typeof privatehomeRouteRouteWithChildren
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privateBudgetIdRouteRoute: privateBudgetIdRouteRouteWithChildren,
  privatehomeRouteRoute: privatehomeRouteRouteWithChildren,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
  LoginOtpIndexRoute: typeof LoginOtpIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
  LoginOtpIndexRoute: LoginOtpIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateRouteRoute: privateRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
